from grammar_rule import GrammarRule

rules = []

def addRule(
  pattern = "",
  suggestion = "",
  short_comment = "",
  full_comment = "",
  exceptions = {}):

  global rules

  rules.append(
    GrammarRule(pattern, suggestion, short_comment, full_comment, exceptions)
  )

# rules.append( GrammarRule(pattern, suggestion, short_comment, full_comment, exceptions) )

# The following rules were derived from Graviax
# created by Matthew J. Strawbridge 2005, GNU Less General Public License
# https://sourceforge.net/projects/graviax/

from grammar_rule import GrammarRule

rules = []

# rules.append( GrammarRule(pattern, suggestion, short_comment, full_comment, exceptions) )

cliche_patterns = [

  # The following rules were derived from Graviax
  # created by Matthew J. Strawbridge 2005, GNU Less General Public License
  # https://sourceforge.net/projects/graviax/

  # en-GB-cliches.xml

  r"\bleave no stone unturned\b",
  r"\blike a bull in a china shop\b",
  r"\bis no exception\b",

  # The following rules were taken a page titled "CLICHE'S: AVOID THEM LIKE THE PLAGUE."
  # Author has permitted redistribution as long as they are given credit.
  # Also need to site their e-mail address and web address

  # Web Page: http://suspense.net/whitefish/cliche.htm
  # Email: suspense@suspense.net 

  r"\bace in the hole\b",
  r"\bace up your sleeve\b",
  r"\bacid test\b",
  r"\bairing dirty laundry\b",
  r"\ball in a day's work\b",
  r"\ball talk, no action\b",
  r"\ball booster, no payload\b",
  r"\ball hat, no cattle\b",
  r"\ball foam, no beer\b",
  r"\ball hammer, no nail\b",
  r"\ball icing, no cake\b",
  r"\ball lime and salt, no tequila\b",
  r"\ball missile, no warhead\b",
  r"\ball shot, no powder\b",
  r"\ball sizzle, no steak\b",
  r"\ball wax and no wick\b",
  r"\ball that and a bag of chips\b",
  r"\ball thumbs\b",
  r"\ball wet\b",
  r"\ball's fair in love and war\b",
  r"\balmighty dollar\b",
  r"\balways a bridesmaid\b",
  r"\bambulance chaser\b",
  r"\banother day, another dollar\b",
  r"\bants in your pants\b",
  r"\bapple-pie order\b",
  r"\barm and a leg\b",
  r"\barmchair quarterback\b",
  r"\barmy brat\b",
  r"\bart imitates life\b",
  r"\bartsy-craftsy\b",
  r"\bartsy-fartsy\b",
  r"\bas luck would have it\b",
  r"\bas old as time\b",
  r"\bat loggerheads\b",
  r"\bbabe in the woods\b",
  r"\bback against the wall\b",
  r"\bback in the saddle\b",
  r"\bback to square one\b",
  r"\bback to the drawing board\b",
  r"\bbad to the bone\b",
  r"\bbadge of honor\b",
  r"\bBadonkadonk\b",
  r"\bballpark figure\b",
  r"\bballs to the wall\b",
  r"\bbaptism of fire\b",
  r"\bbare bones\b",
  r"\bbark is worse than the bite\b",
  r"\bbark up the wrong tree\b",
  r"\bbat out of hell\b",
  r"\bbats in the belfry\b",
  r"\bbattle royal\b",
  r"\bbeat around the bush\b",
  r"\bbeat the bushes\b",
  r"\bbeats me\b",
  r"\bbehind the eight ball\b",
  r"\bbent out of shape\b",
  r"\bbest foot forward\b",
  r"\bbet your bottom dollar\b",
  r"\bbetter half\b",
  r"\bbetter late than never\b",
  r"\bbetter mousetrap\b",
  r"\bbetter safe than sorry\b",
  r"\bbetter than ever\b",
  r"\bbetter the Devil you know\b",
  r"\bbetween a rock and a hard place\b",
  r"\bbeyond the pale\b",
  r"\bbib and tucker\b",
  r"\bbig as life\b",
  r"\bbig fish in a small pond\b",
  r"\bbig man on campus\b",
  r"\bbird in the hand\b",
  r"\bbirds and the bees\b",
  r"\bbirds of the feather\b",
  r"\bbite the dust\b",
  r"\bbite your tongue\b",
  r"\bbitter disappointment\b",
  r"\bblack as coal\b",
  r"\bblast from the past\b",
  r"\bbleeding heart\b",
  r"\bblind as a bat\b",
  r"\bblood is thicker than water\b",
  r"\bblood money\b",
  r"\bblood on your hands\b",
  r"\bblood sweat and tears\b",
  r"\bblow this pop stand\b",
  r"\bblow this joint\b",
  r"\bblushing bride\b",
  r"\bboil it down to\b",
  r"\bbone of contention\b",
  r"\bbooze and broads\b",
  r"\bbored to tears\b",
  r"\bborn and raised\b",
  r"\bborn with a silver spoon in your mouth\b",
  r"\bborn yesterday\b",
  r"\bbottom line\b",
  r"\bbrain drain\b",
  r"\bbrain dump\b",
  r"\bbrass tacks\b",
  r"\bbring home the bacon\b",
  r"\bbroken record\b",
  r"\bbull by the horns\b",
  r"\bbull in a china shop\b",
  r"\bbump in the night\b",
  r"\bbusy as a bee\b",
  r"\bbut seriously\b",
  r"\bby and large\b",
  r"\bcalm before the storm\b",
  r"\bcandle at both ends\b",
  r"\bcan't cut the mustard\b",
  r"\bcase of mistaken identity\b",
  r"\bcat out of the bag\b",
  r"\bcat got your tongue\b",
  r"\bcaught red-handed\b",
  r"\bchapter and verse\b",
  r"\bcheckered career\b",
  r"\bchickens come home to roost\b",
  r"\bchomping at the bit\b",
  r"\bcleanliness is next to godliness\b",
  r"\bclear as a bell\b",
  r"\bclear as mud\b",
  r"\bcold shoulder\b",
  r"\bcommunist conspiracy\b",
  r"\bconniption fit\b",
  r"\bcould care less\b",
  r"\bcouldn't care less\b",
  r"\bcouldn't get to first base\b",
  r"\bcount your blessings\b",
  r"\bcountless hours\b",
  r"\bcreature comfort\b",
  r"\bcrime in the street\b",
  r"\bcuriosity killed the cat\b",
  r"\bcurry favor\b",
  r"\bcut a fine figure\b",
  r"\bcut and dried\b",
  r"\bcut to the chase\b",
  r"\bcut to the quick\b",
  r"\bcute as a button\b",
  r"\bdarkest before the dawn\b",
  r"\bdead as a doornail\b",
  r"\bdeath and destruction\b",
  r"\bdeath and taxes\b",
  r"\bdeath's doorstep\b",
  r"\bdevil is in the details\b",
  r"\bdim view\b",
  r"\bdog days\b",
  r"\bdog in the manger\b",
  r"\bdon't count your chickens before they're hatched\b",
  r"\bdon't do the crime if you can't do the time\b",
  r"\bdoubting Thomas\b",
  r"\bdown and dirty\b",
  r"\bdown in the dumps\b",
  r"\bdown pat\b",
  r"\bdown the drain\b",
  r"\bdown the toilet\b",
  r"\bdown the hatch\b",
  r"\bdown to earth\b",
  r"\bdrive you up a wall\b",
  r"\bdutch uncle\b",
  r"\bdyed in the wool\b",
  r"\bE-ticket\b",
  r"\bear to the ground\b",
  r"\bearly bird catches the worm\b",
  r"\beasier said than done\b",
  r"\beasy as 1-2-3\b",
  r"\beasy as pie\b",
  r"\beat crow\b",
  r"\beat humble pie\b",
  r"\benough already\b",
  r"\beven money\b",
  r"\bevery dog has its day\b",
  r"\bevery fiber of my being\b",
  r"\beverything but the kitchen sink\b",
  r"\bevil twin\b",
  r"\bexistential angst\b",
  r"\bexperts agree\b",
  r"\beye for an eye\b",
  r"\bfacts of life\b",
  r"\bfair-haired one\b",
  r"\bfair weather friend\b",
  r"\bfall off of a turnip truck\b",
  r"\bfat slob\b",
  r"\bfavor us with a song\b",
  r"\bfear and loathing\b",
  r"\bfeather your nest\b",
  r"\bfellow traveler\b",
  r"\bfew and far between\b",
  r"\bfield this one\b",
  r"\bfifteen minutes of fame\b",
  r"\bfish nor fowl\b",
  r"\bfly by night\b",
  r"\bfly the coop\b",
  r"\bfor the birds\b",
  r"\bfox in the henhouse\b",
  r"\bfreudian slip\b",
  r"\bfun and games\b",
  r"\bfun in the sun\b",
  r"\bgarbage in, garbage out\b",
  r"\bget the sack\b",
  r"\bget your groove back\b",
  r"\bgets my goat\b",
  r"\bgift horse in the mouth\b",
  r"\bgilding the lily\b",
  r"\bgive a damn\b",
  r"\bgive me a break\b",
  r"\bgives me the creeps\b",
  r"\bgo him one better\b",
  r"\bgoes without saying\b",
  r"\bgood deed for the day\b",
  r"\bgood time was had by all\b",
  r"\bgreek to me\b",
  r"\bgreen thumb\b",
  r"\bgreen-eyed monster\b",
  r"\bgrist for the mill\b",
  r"\bguiding light\b",
  r"\bhair of the dog\b",
  r"\bhard to believe\b",
  r"\bhave a nice day\b",
  r"\bhead honcho\b",
  r"\bheart's content\b",
  r"\bhell-bent for leather\b",
  r"\bhidden agenda\b",
  r"\bhigh and the mighty (the)\b",
  r"\bhigh on the hog\b",
  r"\bhold a candle to\b",
  r"\bhold your horses\b",
  r"\bhold your tongue\b",
  r"\bhook or by crook\b",
  r"\bhorse of a different color\b",
  r"\bhot knife through butter\b",
  r"\bhow goes the battle?\b",
  r"\bI beg to differ\b",
  r"\bif the shoe fits\b",
  r"\bI'm okay, you're okay\b",
  r"\bin a nutshell\b",
  r"\bin a pinch\b",
  r"\bin a wink\b",
  r"\bin harm's way\b",
  r"\bin the tank\b",
  r"\bin your dreams\b",
  r"\bin your face\b",
  r"\binexorably drawn\b",
  r"\binfo dump\b",
  r"\binfluence peddling\b",
  r"\bintents and purposes\b",
  r"\bit was a dark and stormy night\b",
  r"\bit won't fly\b",
  r"\bJack of all trades\b",
  r"\bjockey for position\b",
  r"\bJohnny-come-lately\b",
  r"\bjoined at the hip\b",
  r"\bjump down your throat\b",
  r"\bjump in with both feet\b",
  r"\bjump on the bandwagon\b",
  r"\bjump the gun\b",
  r"\bjump her bones\b",
  r"\bjump his bones\b",
  r"\bjunk in the trunk\b",
  r"\bjury is still out\b",
  r"\bjustice is blind\b",
  r"\bkeep an eye on you\b",
  r"\bkeep it down\b",
  r"\bkeep it simple, stupid\b",
  r"\bkeep up with the Joneses\b",
  r"\bkeep your cards close to vest\b",
  r"\bkeep your chin up\b",
  r"\bkeep your fingers crossed\b",
  r"\bkeep your powder dry\b",
  r"\bkick ass\b",
  r"\bkickbutt\b",
  r"\bkick the bucket\b",
  r"\bkick up your heels\b",
  r"\bkick you to the curb\b",
  r"\bkick your feet up\b",
  r"\bkid in a candy store\b",
  r"\bkill two birds with one stone\b",
  r"\bKing's English\b",
  r"\bking's ransom\b",
  r"\bkiss and tell\b",
  r"\bkiss ass\b",
  r"\bkiss of death\b",
  r"\bkit and kaboodle\b",
  r"\bknee-high to a grasshopper\b",
  r"\bknock it out of the park\b",
  r"\bknock on wood\b",
  r"\bknock your socks off\b",
  r"\bknocked up\b",
  r"\bknow him from Adam\b",
  r"\bknow the ropes\b",
  r"\bknow the score\b",
  r"\bknuckle down\b",
  r"\bknuckle sandwich\b",
  r"\bknuckle under\b",
  r"\blabor of love\b",
  r"\blap of luxury\b",
  r"\blast but not least\b",
  r"\blast-ditch effort\b",
  r"\blast hurrah\b",
  r"\blaw of the jungle\b",
  r"\blaw of the land\b",
  r"\blay down the law\b",
  r"\bleaps and bounds\b",
  r"\blet sleeping dogs lie\b",
  r"\blet the cat out of the bag\b",
  r"\blet's split\b",
  r"\bliberal media\b",
  r"\blie like a rug\b",
  r"\blife and limb\b",
  r"\blife imitates art\b",
  r"\blife's a bitch\b",
  r"\blighten up\b",
  r"\blights out\b",
  r"\blike a sore thumb\b",
  r"\blike butter\b",
  r"\blike the plague\b",
  r"\blike there's no tomorrow\b",
  r"\blion's share\b",
  r"\blitmus test\b",
  r"\blittle black book\b",
  r"\blive and learn\b",
  r"\blong and short of it\b",
  r"\blong lost love\b",
  r"\blook before you leap\b",
  r"\blounge lizard\b",
  r"\bloved and lost\b",
  r"\blow man on the totem pole\b",
  r"\bluck of the draw\b",
  r"\bluck of the Irish\b",
  r"\bmake my day\b",
  r"\bmale chauvinist\b",
  r"\bman's best friend\b",
  r"\bmany moons\b",
  r"\bmany-splendored thing\b",
  r"\bmark my words\b",
  r"\bmeaningful relationship\b",
  r"\bmellow out\b",
  r"\bmoment of glory\b",
  r"\bmoment's respite\b",
  r"\bMonday morning quarterback\b",
  r"\bmonkey suit\b",
  r"\bmonkey see, monkey do\b",
  r"\bmotherhood and apple pie\b",
  r"\bmovers and shakers\b",
  r"\bmoving experience\b",
  r"\bmy two cents\b",
  r"\bneat as a pin\b",
  r"\bneedless to say\b",
  r"\bnip it in the bud\b",
  r"\bno guts, no glory\b",
  r"\bno love lost\b",
  r"\bno pain, no gain\b",
  r"\bno stone unturned\b",
  r"\bno time like the present\b",
  r"\bnose to the grindstone\b",
  r"\bnot in my back yard\b",
  r"\bnot on your tintype\b",
  r"\bnumber one fan\b",
  r"\bnumerous to mention\b",
  r"\boff the wagon\b",
  r"\bold college try\b",
  r"\bold meets new\b",
  r"\bolder and wiser\b",
  r"\bolder than dirt\b",
  r"\bolder than Methuselah\b",
  r"\bon the bandwagon\b",
  r"\bon the nose\b",
  r"\bon the wagon\b",
  r"\bon thin ice\b",
  r"\bone born every minute\b",
  r"\bone foot in the grave\b",
  r"\bone in a million\b",
  r"\bonly game in town\b",
  r"\bonly to be met\b",
  r"\bout of pocket\b",
  r"\bout of the frying pan\b",
  r"\bout on a limb\b",
  r"\bp's and q's\b",
  r"\bpain and suffering\b",
  r"\bpanic button\b",
  r"\bparty pooper\b",
  r"\bpatter of little feet\b",
  r"\bpass the sniff test\b",
  r"\bpay through the nose\b",
  r"\bpeas in a pod\b",
  r"\bperfect storm\b",
  r"\bpig in a poke\b",
  r"\bpillar of society\b",
  r"\bpinko\b",
  r"\bplenty of fish in the sea\b",
  r"\bpoison pen\b",
  r"\bpoor as a churchmouse\b",
  r"\bpoor excuse for\b",
  r"\bpot calling the kettle black\b",
  r"\bproud possessor\b",
  r"\bput my foot down\b",
  r"\bput your foot down\b",
  r"\bquick as a bunny\b",
  r"\bquick and the dead\b",
  r"\bradical chic\b",
  r"\brags to riches\b",
  r"\braining buckets\b",
  r"\braining cats and dogs\b",
  r"\brank and file\b",
  r"\bread my lips\b",
  r"\bred herring\b",
  r"\bredheaded stepchild\b",
  r"\breign supreme\b",
  r"\bremember the alamo\b",
  r"\broad to hell is paved with good intentions\b",
  r"\brob Peter to pay Paul\b",
  r"\brock and a hard place\b",
  r"\brocket science\b",
  r"\brocket scientist\b",
  r"\brope a dope\b",
  r"\brun it up the flagpole\b",
  r"\brunning dog lackey\b",
  r"\bsafe than sorry\b",
  r"\bsalt of the earth\b",
  r"\bsave face\b",
  r"\bscared stiff\b",
  r"\bscared to death\b",
  r"\bschool's out\b",
  r"\bscreaming meemies\b",
  r"\bsenses reel\b",
  r"\bset the record straight\b",
  r"\bshake a stick should of\b",
  r"\bshoulder to the wheel\b",
  r"\bshouldered his way\b",
  r"\bshut your trap\b",
  r"\bsigh of relief\b",
  r"\bsignificant other\b",
  r"\bsilence is golden\b",
  r"\bslept like a log\b",
  r"\bsmall world\b",
  r"\bsnake in the grass\b",
  r"\bsnow job\b",
  r"\bsnug as a bug\b",
  r"\bsome of my best friends\b",
  r"\bsomething the cat dragged in\b",
  r"\bspade a spade\b",
  r"\bspare the rod\b",
  r"\bspitting image\b",
  r"\bspring to life\b",
  r"\bsqueaky wheel gets the grease\b",
  r"\bsqueaky wheel gets the oil\b",
  r"\bstart from scratch\b",
  r"\bstick in the mud\b",
  r"\bstick in your craw\b",
  r"\bstill waters run deep\b",
  r"\bstop and smell the roses\b",
  r"\bstore bought\b",
  r"\bstranger than fiction\b",
  r"\bstraw that broke the camel's back\b",
  r"\bstubborn as a mule\b",
  r"\bstuff that dreams are made of\b",
  r"\bstuffed shirt\b",
  r"\btake one for the team\b",
  r"\btake the bull by the horns\b",
  r"\btake the plunge\b",
  r"\btakes one to know one\b",
  r"\btalk turkey\b",
  r"\bten foot pole\b",
  r"\bthe earth moved\b",
  r"\bthe final analysis\b",
  r"\bthe real McCoy\b",
  r"\bthe same old story\b",
  r"\bthese things happen\b",
  r"\bthick as thieves\b",
  r"\bthink outside of the box\b",
  r"\bthird time's the charm\b",
  r"\bthis day and age\b",
  r"\bthis point in time\b",
  r"\bthree strikes and you're out\b",
  r"\bthrough the grapevine\b",
  r"\bthrow in the towel\b",
  r"\btiger by the tail\b",
  r"\btill the fat lady sings\b",
  r"\btime and time again\b",
  r"\btime is of the essense\b",
  r"\btip of the iceberg\b",
  r"\b'tis the season\b",
  r"\bto err is human\b",
  r"\bto the best of my knowledge\b",
  r"\btongue-in-cheek\b",
  r"\btoo hot to handle\b",
  r"\btouch of blarney\b",
  r"\btough as nails\b",
  r"\btough luck\b",
  r"\btough row to hoe\b",
  r"\btraditional family values\b",
  r"\btrials and tribulations\b",
  r"\btried and true\b",
  r"\btrip down memory lane\b",
  r"\btrue blue\b",
  r"\bturn your smile upside-down\b",
  r"\bturn your frown upside-down\b",
  r"\btwist of fate\b",
  r"\btwists and turns\b",
  r"\btwo to tango\b",
  r"\bunder the gun\b",
  r"\bunder the same roof\b",
  r"\bunderstated elegance\b",
  r"\bunexpected twist\b",
  r"\buntil the cows come home\b",
  r"\bup his sleeve\b",
  r"\bup the creek\b",
  r"\bup the wrong tree\b",
  r"\bvery real concern\b",
  r"\bview with alarm\b",
  r"\bwakeup call\b",
  r"\bwas my face red\b",
  r"\bwatch your tongue\b",
  r"\bweb of intrigue\b",
  r"\bweek of sundays\b",
  r"\bwhat a bummer\b",
  r"\bwhat comes around, goes around\b",
  r"\bwhat the cat dragged in\b",
  r"\bwhat the dickens\b",
  r"\bwhat the heck\b",
  r"\bwhat the hell\b",
  r"\bwhat you see is what you get\b",
  r"\bwhat's not to like\b",
  r"\bwheeler-dealer\b",
  r"\bwhen in doubt, punt\b",
  r"\bwhen push comes to shove\b",
  r"\bwhen rubber meets the road\b",
  r"\bwhen the cat's away\b",
  r"\bwhen the going gets tough, the tough get going\b",
  r"\bwho has everything\b",
  r"\bwhole ball of wax\b",
  r"\bwhole hog\b",
  r"\bwhole nine yards\b",
  r"\bwhole other story\b",
  r"\bwild goose chase\b",
  r"\bwild oats\b",
  r"\bwill wonders never cease\b",
  r"\bwimp\b",
  r"\bwin friends and influence people\b",
  r"\bwin one for the Gipper\b",
  r"\bwnning is everything\b",
  r"\bwisdom of the ages\b",
  r"\bwithout benefit of clergy\b",
  r"\bwolf at the door\b",
  r"\bwords fail\b",
  r"\bwork like a dog\b",
  r"\bworst nightmare\b",
  r"\bwrong side of the bed\b",
  r"\byears young\b",
  r"\byellow journalism\b",
  r"\byou are what you eat\b",
  r"\byou can run, but you can't hide\b",
  r"\byou know what they say\b",
  r"\byoung and foolish\b",
  r"\byoung and restless\b",
  r"\byuppie\b",
  r"\b20/20 hindsight\b",
  r"\bHis elevator doesn't go to the top floor\b",
  r"\bAll foam, no beer\b",
  r"\bHis bread ain't done\b",
  r"\bHis yeast went bad\b",
  r"\bHe couldn't pour water out of a boot with instructions printed on the heel\b",
  r"\bThe cheese slid off his cracker\b",
  r"\bHe's One taco short of a combination plate\b",
  r"\bHe's One brick shy of a load\b",
  r"\bHe's One pickle short of a barrel\b",
  r"\bHe's One sandwich short of a picnic\b",
  r"\bHe's One step short of a flight\b",
  r"\bHe's One step short of a flight of stairs\b",
  r"\bHe's One fry short of a Happy Meal\b",
  r"\bThe light is on, but nobody is home.\b",
  r"\bThere's nothing in the attic but cobwebs.\b",
  r"\bHe's not the sharpest knife in the drawer.\b",
  r"\bHe's not the brightest crayon in the box.\b",
  r"\bThe wheel is turning, but the hamster is dead.\b",
  r"\bBody by Fisher, brains by Mattel.\b",
  r"\bThe gates are down, the lights are flashing, but there is no train.\b",
  r"\bHe's dumber than a box of rocks.\b",
  r"\bHe's dumber than a bag of hammers.\b",
  r"\bHe couldn't think his way out of a paper bag.\b",
  r"\bIf you gave him a penny for his thoughts, you'd get change.\b",
  r"\bSomewhere a villiage is missing its idiot\b",
  r"\bHe donated his brain to science. Science sent it back.\b",
  r"\bHe fell out of the Stupid Tree and hit every branch on his way down.\b",
  r"\bThe starting gate is open, but he's still asking directions.\b",
  r"\bA few cans short of a six-pack.\b",
  r"\bHis pilot light isn't lit.\b",
  r"\bIf brains were dynamite, he couldn't blow his nose.\b",
  r"\bIt takes him an hour to cook Minute Rice.\b"]

for cliche_pattern in cliche_patterns:
  addRule(
    pattern = cliche_pattern,
    suggestion = "",
    short_comment = "Cliche",
    full_comment = "You should avoid using cliches.")


